@SampleShopApi_HostAddress = http://localhost:5261

### 

GET {{SampleShopApi_HostAddress}}/songs?sort=price&search=new
Accept: application/json

###

POST {{SampleShopApi_HostAddress}}/songs
Content-Type: application/json

{
	"name": "New Song",
	"price": 9.99,
	"description": "A brand new song"
}