// <auto-generated />
using System;
using App.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace SampleShopApi.App.Data.migrations {
  [DbContext(typeof(ShopApiContext))]
  [Migration("20251103145511_CreateCart")]
  partial class CreateCart {
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder) {
#pragma warning disable 612, 618
      modelBuilder
          .HasAnnotation("ProductVersion", "9.0.10")
          .HasAnnotation("Relational:MaxIdentifierLength", 63);

      NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

      modelBuilder.Entity("App.Cart.Cart", b => {
        b.Property<int>("Id")
            .ValueGeneratedOnAdd()
            .HasColumnType("integer");

        NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

        b.Property<DateTime>("CreatedAt")
            .HasColumnType("timestamp with time zone");

        b.Property<DateTime>("UpdatedAt")
            .HasColumnType("timestamp with time zone");

        b.HasKey("Id");

        b.ToTable("Carts");
      });

      modelBuilder.Entity("App.Cart.CartItem", b => {
        b.Property<int>("Id")
            .ValueGeneratedOnAdd()
            .HasColumnType("integer");

        NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

        b.Property<int>("CartId")
            .HasColumnType("integer");

        b.Property<int>("ProductId")
            .HasColumnType("integer");

        b.Property<int>("Quantity")
            .HasColumnType("integer");

        b.HasKey("Id");

        b.HasIndex("CartId");

        b.HasIndex("ProductId");

        b.ToTable("CartItems");
      });

      modelBuilder.Entity("SampleShopApi.App.Entities.Products.Product", b => {
        b.Property<int>("Id")
            .ValueGeneratedOnAdd()
            .HasColumnType("integer");

        NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

        b.Property<string>("Description")
            .IsRequired()
            .HasColumnType("text");

        b.Property<string>("Name")
            .IsRequired()
            .HasColumnType("text");

        b.Property<decimal>("Price")
            .HasColumnType("numeric");

        b.HasKey("Id");

        b.ToTable("Products");
      });

      modelBuilder.Entity("App.Cart.CartItem", b => {
        b.HasOne("App.Cart.Cart", "Cart")
            .WithMany("Items")
            .HasForeignKey("CartId")
            .OnDelete(DeleteBehavior.Cascade)
            .IsRequired();

        b.HasOne("SampleShopApi.App.Entities.Products.Product", "Product")
            .WithMany()
            .HasForeignKey("ProductId")
            .OnDelete(DeleteBehavior.Cascade)
            .IsRequired();

        b.Navigation("Cart");

        b.Navigation("Product");
      });

      modelBuilder.Entity("App.Cart.Cart", b => {
        b.Navigation("Items");
      });
#pragma warning restore 612, 618
    }
  }
}
